// var a: number;
// var b: boolean;
// var c: string;
// a = 111;
// b = true;
// c = "hello world";
// let myArr: number[] = [1, 2, 3];
var myArr = [false, false, true];
// myArr = [];
myArr.push(false);
var a = myArr.pop();
console.log(a);
var my_name = "rails365";
var other_name = my_name;
console.log(other_name);
